### ISSUE TITLE
jerking animation 1.75

### ISSUE THREAD

**Issue by CloudeLecaw** [TheClowner/ccRides-Support#43]
first issue come when multiple ccrides started at same time and stop at different time.
the animations of it begang jerking like whild and you feel like you just play with 3 fps while watching or sitting in them
the rest of the server works normal its just the reides that jerk like that..

maybe this needs some adjustment
ccrides 1.7.5
papermc 1.18.2

```
*[15:32:05 INFO]: Cloude_Lecaw issued server command: /ccrides:rideadmin disableall
[15:32:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ccrides:rideadmin' in plugin ccRides v1.7.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-255]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-255]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-255]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-255]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1447) ~[paper-1.18.2.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-255]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at net.clownercraft.ccRides.rides.Ride.disable(Ride.java:1166) ~[ccRides_1.7.5.jar:?]
        at net.clownercraft.ccRides.commands.AdminCommandExecutor.onCommand(AdminCommandExecutor.java:193) ~[ccRides_1.7.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

**Comment by TheClowner** [comment]
I've not had a chance to test against 1.18.2 myself yet, but it'd be helpful to see a video of the issue you're having. 

Also, that error I believe is unrelated to the main issue, but I should fix that anyway - that bit's easier to track down that jerky motion :)

**Comment by TheClowner** [comment]
Okay, I've just tested on the latest build (#260) of paper 1.18.2, and not seen this issue at all. 

If you're running an older build of paper, can I ask you to update and see if the issue persists?

**Comment by CloudeLecaw** [comment]
you need minimum two players for this
One that is riding and one that is next to him (so in the same junk)
when the player is alone it seems not to happen

https://streamable.com/qtnkvj

what u dont see in the video is thatamother player is riding the ride there at this moment where i took the video

i tped to him and like before the jerk started after i went to him
when i leave him then its near normal anymore.


here i made a little one with me alone - you will see it wents normal

https://streamable.com/myknca

**Comment by CloudeLecaw** [comment]
We Tested it a bit more

It looks like all rides that using chains (i aspect these are the armorstands that design the arms) are effected

So here is want is "needed"
- A bigger carusell with arms (like the big weel)
- two players on the same ride.

**Comment by TheClowner** [comment]
I find it very odd that just having a second player nearby causes the problem - and suspect it's more likely something wrong on the spigot/paper side, although I'm not sure what exactly. I haven't got time at the moment to do any testing myself, but can I get you to check a couple of things:

- If you (alone) ride the ride, rather than just watching it from a distance, is it still smooth then?
- With that enterprise ride in the video - if you set `SHOW_ARM` and `SHOW_SPOKES` to false (which should leave you only with the minecarts) - does the issue still occur?
- Can you send your full output of `/version`?
- Are you on the same client version as the server (ie, not using ViaVersion or Bedrock crossplay to join)?

**Comment by CloudeLecaw** [comment]
Well we use oonly vanilla Client with paper both on 1.18.2
I will do these test today and reply you with the results :)

**Comment by CloudeLecaw** [comment]
Hey there its me.
Your right about it
i disabled SHOW_ARM and SHOW_SPOKES from the Enterprice ride aand from one moment to the next the Ride wents normal like we settet it up!
https://streamable.com/zcxnzl

Now i reenabled the arms SHOW_ARMs - Y Result the ride is still working nice..may a minimal bit lower...but still ok that we could life with it ;)
https://streamable.com/gkux8m

.
.
But when i reenaled the SHOW_SPOKES then the jerking effect starts aggain.


The Same jerking we have when we set SHOW_LEAD_CHAINS and SHOW_ITEM_CHAINS on the carusell to true


Like we thought llready for all rides.. when hidding the parts that are made with moveing hidden armorstands then this jerking not happens. Else it struckels. and starts jerking with crazzy when a secound player is there..

After setting the armorstand parts to false (mostly chains and simlars setting then the issue is gone

.
.

![image](https://user-images.githubusercontent.com/12080017/163068362-acfbcd61-5dba-4a2b-8f22-9edf0ed11abe.png)


On our server we just acccept vanilla clients that are equal to the server versions. means only 1.18.2 players with vanilla clients (if its not a faked brand from a hacked one) The Onlinemode is true. Wie also dont use plugins like viaversion or visevia or what else the are called. So the users must be 1.18.2 clients too.

**Comment by CloudeLecaw** [comment]
it magicly disapeart after we changed to paper 1.19 (well also with 1.7.6 version too)
So i cant tell you if it was just an issue with 1.18.x or maybe improvemnts in latest version :)

So i can close this now :)
